import { useLang, text } from '../context/LangContext'

const faqs = [
  ['Combien de temps prend le traitement d’une demande ?', 'How long does a request take to process?', 'Le délai varie selon le service, généralement entre 1 et 10 jours ouvrés après confirmation du paiement.', 'The timeline depends on the service, usually between 1 and 10 business days after payment is confirmed.'],
  ['Quels formats de fichiers sont acceptés ?', 'Which file formats are accepted?', 'Les formats acceptés et la taille maximale sont indiqués sur chaque champ de votre demande.', 'Accepted formats and maximum size are shown on every field in your request.'],
  ['Comment puis-je payer ?', 'How can I pay?', 'Après votre demande, les differents methodes de paiement accepter sont indiquer dans la section "comment ca marche" et pourrez envoyer votre preuve via WhatsApp.', 'After your request, the available payment methods will be indicated in the "how it works" section, and you can send your proof through WhatsApp.'],
  ['Puis-je suivre ma commande sans compte ?', 'Can I track my order without an account?', 'Oui. Utilisez simplement votre référence de commande depuis la page Suivi.', 'Yes. Simply use your order reference from the tracking page.']
]
export default function FAQ() { const { lang } = useLang(); return <div className="mx-auto max-w-2xl px-4 py-12"><div className="mb-8 text-center"><p className="text-sm font-bold uppercase tracking-wider text-oasis-green-dark">{text(lang, 'Besoin d’aide ?', 'Need help?')}</p><h1 className="mt-2 text-3xl font-extrabold">{text(lang, 'Questions fréquentes', 'Frequently asked questions')}</h1></div><div className="space-y-3">{faqs.map(([fq, eq, fa, ea]) => <details key={fq} className="card group cursor-pointer"><summary className="flex list-none items-center justify-between font-bold text-slate-800">{text(lang, fq, eq)}<span className="ml-4 text-xl text-oasis-blue transition group-open:rotate-45">+</span></summary><p className="mt-3 border-t border-slate-100 pt-3 text-sm leading-6 text-slate-600">{text(lang, fa, ea)}</p></details>)}</div></div> }
